Algoritmo "repeticao1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ricardo Corrêa e Lucas Calu
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/03/2024
Var
// Seção de Declarações das variáveis 
   x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   PARA x de 1 ate 20 FACA
       ESCREVAL("Número ", x)
   FIMPARA

Fimalgoritmo